development:
  adapter: postgresql
  encoding: unicode
  database: pro-angular_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pro-angular_test
  pool: 5
  host: localhost
